package byxx.resource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-29T08:57:32.203+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "PbInterface", 
                  wsdlLocation = "http://10.128.20.240:7003/LumsSoapWs/PbResource?wsdl",
                  targetNamespace = "http://resource.byxx/") 
public class PbInterface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resource.byxx/", "PbInterface");
    public final static QName PbResourceImplPort = new QName("http://resource.byxx/", "PbResourceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.128.20.240:7003/LumsSoapWs/PbResource?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PbInterface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.128.20.240:7003/LumsSoapWs/PbResource?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PbInterface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PbInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PbInterface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbInterface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbInterface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PbInterface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PbResource
     */
    @WebEndpoint(name = "PbResourceImplPort")
    public PbResource getPbResourceImplPort() {
        return super.getPort(PbResourceImplPort, PbResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PbResource
     */
    @WebEndpoint(name = "PbResourceImplPort")
    public PbResource getPbResourceImplPort(WebServiceFeature... features) {
        return super.getPort(PbResourceImplPort, PbResource.class, features);
    }

}
