package byxx.resource;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-29T08:57:32.154+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://resource.byxx/", name = "PbResource")
@XmlSeeAlso({ObjectFactory.class})
public interface PbResource {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByWorkNoAndTime(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByTimeStr(
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverAlcoholByWorkNoAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverAlcoholByWorkNoAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverAlcoholByWorkNoAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverAlcoholByWorkNoAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverAlcoholPojo> getDriverAlcoholByWorkNoAndTimeStr(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByHouseCodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByHouseCodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByHouseCodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByHouseCodeAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByHouseCodeAndTimeStr(
        @WebParam(name = "houseCode", targetNamespace = "")
        java.lang.String houseCode,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLocoAndLowercodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoAndLowercodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercodeAndTimeStrResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLocoAndLowercodeAndTimeStr(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco,
        @WebParam(name = "lowercode", targetNamespace = "")
        java.lang.String lowercode,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNoAndDispmancode", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancode")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoAndDispmancodeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancodeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNoAndDispmancode(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLocoAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndTimeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLocoAndTime(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverInfoByDriverId", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoByDriverId")
    @WebMethod
    @ResponseWrapper(localName = "getDriverInfoByDriverIdResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoByDriverIdResponse")
    public byxx.resource.DriverInfoPojo getDriverInfoByDriverId(
        @WebParam(name = "driverId", targetNamespace = "")
        int driverId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndTimeStrAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndTimeStrAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndTimeStrAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndTimeStrAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndDispManCodeAndTimeStrAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverFingerByWorkNoList", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByWorkNoList")
    @WebMethod
    @ResponseWrapper(localName = "getDriverFingerByWorkNoListResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByWorkNoListResponse")
    public java.util.List<byxx.resource.DriverFingerPojo> getDriverFingerByWorkNoList(
        @WebParam(name = "workNos", targetNamespace = "")
        java.util.List<java.lang.Integer> workNos
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNoAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndTimeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNoAndTime(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPlanGroupByClientId", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetPlanGroupByClientId")
    @WebMethod
    @ResponseWrapper(localName = "getPlanGroupByClientIdResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetPlanGroupByClientIdResponse")
    public java.util.List<byxx.resource.PlanGroupPojo> getPlanGroupByClientId(
        @WebParam(name = "clientId", targetNamespace = "")
        java.lang.String clientId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverFingerBySectionCode", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerBySectionCode")
    @WebMethod
    @ResponseWrapper(localName = "getDriverFingerBySectionCodeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerBySectionCodeResponse")
    public java.util.List<byxx.resource.DriverFingerPojo> getDriverFingerBySectionCode(
        @WebParam(name = "secCode", targetNamespace = "")
        java.lang.String secCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLoco", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLoco")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLoco(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByJobIds", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByJobIds")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByJobIdsResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByJobIdsResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByJobIds(
        @WebParam(name = "jobIds", targetNamespace = "")
        java.util.List<java.lang.Integer> jobIds
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByOffDutyInfos", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOffDutyInfos")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByOffDutyInfosResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOffDutyInfosResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByOffDutyInfos(
        @WebParam(name = "workno", targetNamespace = "")
        int workno,
        @WebParam(name = "arvTimeStr", targetNamespace = "")
        java.lang.String arvTimeStr,
        @WebParam(name = "arvTrain", targetNamespace = "")
        java.lang.String arvTrain,
        @WebParam(name = "arvStation", targetNamespace = "")
        java.lang.String arvStation,
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByTimeStrResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByTimeStr(
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByOffDutyCodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOffDutyCodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByOffDutyCodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOffDutyCodeAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByOffDutyCodeAndTimeStr(
        @WebParam(name = "offDutyCode", targetNamespace = "")
        java.lang.String offDutyCode,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWorkplaceNameByCode", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetWorkplaceNameByCode")
    @WebMethod
    @ResponseWrapper(localName = "getWorkplaceNameByCodeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetWorkplaceNameByCodeResponse")
    public java.lang.String getWorkplaceNameByCode(
        @WebParam(name = "workPlaceCode", targetNamespace = "")
        java.lang.String workPlaceCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByHouseCodeAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByHouseCodeAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByHouseCodeAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByHouseCodeAndTimeResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByHouseCodeAndTime(
        @WebParam(name = "houseCode", targetNamespace = "")
        java.lang.String houseCode,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByOnDutyCodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOnDutyCodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByOnDutyCodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByOnDutyCodeAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByOnDutyCodeAndTimeStr(
        @WebParam(name = "onDutyCode", targetNamespace = "")
        java.lang.String onDutyCode,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNoAndDispmancodeAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancodeAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoAndDispmancodeAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancodeAndTimeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNoAndDispmancodeAndTime(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverFingerByWorkNo", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByWorkNo")
    @WebMethod
    @ResponseWrapper(localName = "getDriverFingerByWorkNoResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByWorkNoResponse")
    public java.util.List<byxx.resource.DriverFingerPojo> getDriverFingerByWorkNo(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByDispLocoCodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDispLocoCodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByDispLocoCodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDispLocoCodeAndTimeStrResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByDispLocoCodeAndTimeStr(
        @WebParam(name = "dispLocoCode", targetNamespace = "")
        java.lang.String dispLocoCode,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLocoAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndTimeStrResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLocoAndTimeStr(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLocoAndLowercode", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercode")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoAndLowercodeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercodeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLocoAndLowercode(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco,
        @WebParam(name = "lowercode", targetNamespace = "")
        java.lang.String lowercode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPbTaskNameByTaskId", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetPbTaskNameByTaskId")
    @WebMethod
    @ResponseWrapper(localName = "getPbTaskNameByTaskIdResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetPbTaskNameByTaskIdResponse")
    public java.lang.String getPbTaskNameByTaskId(
        @WebParam(name = "taskdicid", targetNamespace = "")
        int taskdicid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByWorkNoAndTimeStr(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverInfoByWorkNo", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoByWorkNo")
    @WebMethod
    @ResponseWrapper(localName = "getDriverInfoByWorkNoResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoByWorkNoResponse")
    public byxx.resource.DriverInfoPojo getDriverInfoByWorkNo(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByDispManCodeAndTypeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByDispManCodeAndTypeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByDispManCodeAndTypeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByDispManCodeAndTypeAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByDispManCodeAndTypeAndTimeStr(
        @WebParam(name = "dispManCode", targetNamespace = "")
        java.lang.String dispManCode,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByDispLocoCodeAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDispLocoCodeAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByDispLocoCodeAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDispLocoCodeAndTimeResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByDispLocoCodeAndTime(
        @WebParam(name = "dispLocoCode", targetNamespace = "")
        java.lang.String dispLocoCode,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverDutyRecordByWorkNoAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverDutyRecordByWorkNoAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverDutyRecordByWorkNoAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverDutyRecordByWorkNoAndTimeResponse")
    public java.util.List<byxx.resource.DriverDutyPojo> getDriverDutyRecordByWorkNoAndTime(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByDepStationAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDepStationAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByDepStationAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDepStationAndTimeStrResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByDepStationAndTimeStr(
        @WebParam(name = "depStation", targetNamespace = "")
        java.lang.String depStation,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverFingerByDriverId", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByDriverId")
    @WebMethod
    @ResponseWrapper(localName = "getDriverFingerByDriverIdResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByDriverIdResponse")
    public java.util.List<byxx.resource.DriverFingerPojo> getDriverFingerByDriverId(
        @WebParam(name = "driverId", targetNamespace = "")
        int driverId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByLocoAndLowercodeAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercodeAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByLocoAndLowercodeAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByLocoAndLowercodeAndTimeResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByLocoAndLowercodeAndTime(
        @WebParam(name = "model", targetNamespace = "")
        java.lang.String model,
        @WebParam(name = "loco", targetNamespace = "")
        int loco,
        @WebParam(name = "lowercode", targetNamespace = "")
        java.lang.String lowercode,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverInfoBySectionCode", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoBySectionCode")
    @WebMethod
    @ResponseWrapper(localName = "getDriverInfoBySectionCodeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverInfoBySectionCodeResponse")
    public java.util.List<byxx.resource.DriverInfoPojo> getDriverInfoBySectionCode(
        @WebParam(name = "secCode", targetNamespace = "")
        java.lang.String secCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndDispManCodeAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverAlcoholByWorkNoAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverAlcoholByWorkNoAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverAlcoholByWorkNoAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverAlcoholByWorkNoAndTimeResponse")
    public java.util.List<byxx.resource.DriverAlcoholPojo> getDriverAlcoholByWorkNoAndTime(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNo", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNo")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNo(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverDutyRecordByWorkNoAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverDutyRecordByWorkNoAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getDriverDutyRecordByWorkNoAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverDutyRecordByWorkNoAndTimeStrResponse")
    public java.util.List<byxx.resource.DriverDutyPojo> getDriverDutyRecordByWorkNoAndTimeStr(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "beginTimeStr", targetNamespace = "")
        java.lang.String beginTimeStr,
        @WebParam(name = "endTimeStr", targetNamespace = "")
        java.lang.String endTimeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNoAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndTimeStrResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNoAndTimeStr(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndTimeStrAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeStrAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndTimeStrAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeStrAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndTimeStrAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByDepStationAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDepStationAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByDepStationAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByDepStationAndTimeResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByDepStationAndTime(
        @WebParam(name = "depStation", targetNamespace = "")
        java.lang.String depStation,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByTime")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByTimeResponse")
    public java.util.List<byxx.resource.LocoPlanPojo> getLocoPlanByTime(
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndTimeAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndTimeAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTimeAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndTimeAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByDispManCodeAndTypeAndTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByDispManCodeAndTypeAndTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByDispManCodeAndTypeAndTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByDispManCodeAndTypeAndTimeResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByDispManCodeAndTypeAndTime(
        @WebParam(name = "dispManCode", targetNamespace = "")
        java.lang.String dispManCode,
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverFingerByDriverIdList", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByDriverIdList")
    @WebMethod
    @ResponseWrapper(localName = "getDriverFingerByDriverIdListResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverFingerByDriverIdListResponse")
    public java.util.List<byxx.resource.DriverFingerPojo> getDriverFingerByDriverIdList(
        @WebParam(name = "driverIds", targetNamespace = "")
        java.util.List<java.lang.Integer> driverIds
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndTimeAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndTimeAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndDispManCodeAndTimeAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndDispManCodeAndTimeAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndDispManCodeAndTimeAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode,
        @WebParam(name = "time", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar time,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByTime", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByTime")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByTimeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByTimeResponse")
    public java.util.List<byxx.resource.DriverPlanPojo> getDriverPlanByTime(
        @WebParam(name = "beginTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDriverPlanByWorkNoAndType", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndType")
    @WebMethod
    @ResponseWrapper(localName = "getDriverPlanByWorkNoAndTypeResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetDriverPlanByWorkNoAndTypeResponse")
    public byxx.resource.DriverPlanPojo getDriverPlanByWorkNoAndType(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocoPlanByWorkNoAndDispmancodeAndTimeStr", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancodeAndTimeStr")
    @WebMethod
    @ResponseWrapper(localName = "getLocoPlanByWorkNoAndDispmancodeAndTimeStrResponse", targetNamespace = "http://resource.byxx/", className = "byxx.resource.GetLocoPlanByWorkNoAndDispmancodeAndTimeStrResponse")
    public byxx.resource.LocoPlanPojo getLocoPlanByWorkNoAndDispmancodeAndTimeStr(
        @WebParam(name = "workNo", targetNamespace = "")
        int workNo,
        @WebParam(name = "dispmancode", targetNamespace = "")
        java.lang.String dispmancode,
        @WebParam(name = "timeStr", targetNamespace = "")
        java.lang.String timeStr
    );
}
